development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:2a73f6e12e511b1f3370e9e99489ab6d@pike.redistogo.com:11409/
  channel_prefix: mathLab_backend_production
